import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import NextAuthProvider from "@/compononents/NextAuthProvider";
import Navbar from "@/compononents/ui/navbar";

const siteFont = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={`${siteFont.className} bg-gray-50 h-full px-10 `}>
          <div className="h-screen max-w-screen-2xl mx-auto">
            <Navbar />
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
